if GetLocale() ~= "deDE" then return end
local L=MythicHub_L
local T={mhub_title="MYTHISCH+ HUB",mhub_col_dungeon="Dungeon",mhub_col_level="Stein",mhub_col_rating="Wertung",mhub_col_best="Bestzeit",mhub_tp_click="Klicken zum Teleportieren",mhub_tp_not_available="Teleport nicht verfügbar",mhub_tp_not_learned="Dungeon-Teleport nicht erlernt.",mhub_vault_title="GROSSE SCHATZKAMMER",mhub_vault_raids="Schlachtzüge",mhub_vault_dungeons="Dungeons",mhub_vault_world="Welt",mhub_vault_locked="Belohnung noch nicht freigeschaltet",mover_battlerez="Kampf-Wiederbelebung",msg_char_skin_reload="Charakter-Skin: /reload, um alle Änderungen anzuwenden.",tmt_completed_depleted="STEIN NICHT RECHTZEITIG",tmt_completed_on_time="STEIN ABGESCHLOSSEN",tmt_deaths="Tode",tmt_dungeon_unknown="Mythisch+ Dungeon",tmt_forces="Gegnerische Streitkräfte",tmt_forces_done="FERTIG",tmt_forces_remaining="%d verbleibend",tmt_key_none_found="Keine Mythisch+-Steine gefunden",tmt_key_not_available="Schlüssel-Synchronisierung nicht verfügbar",tmt_key_not_in_group="Du bist in keiner Gruppe",tmt_kr_spin="DREHEN",tmt_preview_active="Mythisch+-Tracker-Vorschau aktiviert.",tmt_time_lost="Verlorene Zeit: %s",ts_col_player="Spieler",ts_col_rating="Wertung",ts_col_key_level="Stein",ts_col_key_name="Dungeon",ts_completed="ABGESCHLOSSEN",ts_depleted="NICHT RECHTZEITIG",ts_duration="Dauer",ts_footer_total="Gruppe",ts_footer_players="%d Spieler",ts_mythic_zero="Mythisch 0",ts_no_data="Keine gespeicherten Mythisch+-Daten.",gui_subtitle="Eigenständige Mythisch+-Zentrale",gui_dashboard="Übersicht",gui_tracker="Tracker",gui_keys_score="Steine & Score",gui_character="Charakter & Inspizieren",gui_brez="Kampf-Rez",gui_modules="Module",gui_quick="Schnellaktionen",gui_lock="Elemente sperren",gui_unlock="Elemente entsperren",gui_open_hub="Mythisch+ Hub öffnen",gui_send_keys="Gruppensteine senden",gui_roulette="Schlüssel-Roulette",gui_score_preview="Score-Vorschau",gui_tracker_preview="Tracker-Vorschau",gui_score_last="Letzter Lauf",gui_reset_pos="Position zurücksetzen",gui_enabled="Aktiviert",gui_hide_blizzard="Blizzard-Mythisch+-Tracker ausblenden",gui_show_timer="Timer anzeigen",gui_show_forces="Gegnerkräfte anzeigen",gui_show_bosses="Bosse anzeigen",gui_auto_score="MythicHubScore nach dem Lauf automatisch anzeigen",gui_auto_key="Schlüssel automatisch einsetzen",gui_keysync="Schlüssel mit MythicHub-Nutzern teilen",gui_only_instance="Nur in Instanzen anzeigen",gui_scale="Skalierung",gui_alpha="Deckkraft",gui_font_scale="Schriftskalierung",gui_brez_size="Zählergröße",gui_brez_font="Schriftgröße",gui_advisor="Schlüsselberater",gui_advisor_btn="Nächsten Dungeon vorschlagen",gui_score_name="MythicHubScore",gui_unlock_score="MythicHubScore entsperren",gui_lock_score="MythicHubScore sperren",gui_character_scale="Charakterfenster-Skalierung",
 gui_progression="Fortschritt",gui_run_history="Run-Verlauf",gui_score_planner="Score-Planer / Upgrade-Finder",gui_minimap="Minikarten-Schaltfläche",gui_history_max="Maximal gespeicherte Runs",gui_open_history="Run-Verlauf öffnen",gui_open_planner="Score-Planer öffnen",gui_sync_history="Blizzard-Verlauf synchronisieren",gui_clear_history="Verlauf löschen (Umschalt+Klick)",gui_target_increase="Ziel-Schlüsselanstieg",
 history_title="MythicHub Run-Verlauf",history_sync="Blizzard synchronisieren",history_clear="Verlauf löschen",history_shift_clear="Halte Umschalt gedrückt und klicke auf Verlauf löschen.",history_col_date="Datum",history_col_dungeon="Dungeon",history_col_key="Stein",history_col_time="Zeit",history_col_score="Score",history_col_gain="Gewinn",history_col_status="Status",history_timed="IN ZEIT",history_depleted="NICHT IN ZEIT",history_complete="FERTIG",history_summary="%d Runs  •  %d in Zeit  •  %d depleted  •  %+d Wertung",
 planner_title="MythicHub Score-Planer",planner_subtitle="Upgrade-Finder — ordnet die besten nächsten Mythisch+-Verbesserungen anhand deiner Saisondaten.",planner_refresh="Aktualisieren",planner_overall="Wertung: %d",planner_col_dungeon="Dungeon",planner_col_best="Beste",planner_col_score="Score",planner_col_target="Ziel",planner_col_gain="Gesch. Gewinn",planner_col_action="Reise",planner_tp="TP",planner_estimate_note="Geschätzte Gewinne basieren auf deiner eigenen Saison-Score/Level-Kurve. Die exakte Blizzard-Wertung kann je nach Zeit und Saisonregeln abweichen.",planner_no_data="Noch keine Saisondaten verfügbar.",planner_combat="Der Score-Planer kann im Kampf nicht geöffnet werden.",planner_chat_pick="Upgrade-Finder: %s +%d — geschätzter Gewinn ~+%d.",
 minimap_open_config="Einstellungen öffnen",minimap_open_hub="Mythisch+ Hub öffnen",minimap_open_history="Run-Verlauf öffnen",minimap_open_planner="Score-Planer öffnen",minimap_tooltip="Linksklick: Einstellungen. Rechtsklick: MythicHub-Menü. Ziehen zum Verschieben an der Minikarte.",minimap_compartment_tooltip="Klicken, um das MythicHub-Schnellmenü zu öffnen.",
}
for k,v in pairs(T) do L[k]=v end
