if GetLocale() ~= "frFR" then return end
local L=MythicHub_L
local T={
 mhub_title="HUB MYTHIQUE+",mhub_col_dungeon="Donjon",mhub_col_level="Clé",mhub_col_rating="Score",mhub_col_best="Meilleur",
 mhub_tp_click="Cliquer pour se téléporter",mhub_tp_not_available="Téléportation indisponible",mhub_tp_not_learned="Téléportation du donjon non apprise.",
 mhub_vault_title="GRANDE CHAMBRE-FORTE",mhub_vault_raids="Raids",mhub_vault_dungeons="Donjons",mhub_vault_world="Monde",mhub_vault_locked="Récompense pas encore débloquée",
 mover_battlerez="Résurrection de combat",msg_char_skin_reload="Skin Personnage : /reload pour appliquer tous les changements.",
 tmt_completed_depleted="CLÉ ÉPUISÉE",tmt_completed_on_time="CLÉ TERMINÉE",tmt_deaths="Morts",tmt_dungeon_unknown="Donjon Mythique+",tmt_forces="Forces ennemies",tmt_forces_done="TERMINÉ",tmt_forces_pct="%d%%",tmt_forces_remaining="%d restantes",tmt_key_level="+%d",tmt_key_none_found="Aucune clé Mythique+ trouvée",tmt_key_not_available="Synchronisation des clés indisponible",tmt_key_not_in_group="Vous n'êtes pas dans un groupe",tmt_kr_spin="LANCER",tmt_preview_active="Aperçu du tracker Mythique+ activé.",tmt_time_lost="Temps perdu : %s",
 ts_col_player="Joueur",ts_col_rating="Cote",ts_col_key_level="Clé",ts_col_key_name="Donjon",ts_completed="TERMINÉ",ts_depleted="ÉPUISÉ",ts_duration="Durée",ts_footer_total="Groupe",ts_footer_players="%d joueurs",ts_key_level="+%d",ts_mythic_zero="Mythique 0",ts_no_data="Aucune donnée de run Mythique+ sauvegardée.",
 gui_subtitle="Centre de commande Mythique+ autonome",gui_dashboard="Tableau de bord",gui_tracker="Tracker",gui_keys_score="Clés & Score",gui_character="Personnage & Inspection",gui_brez="Résurrection",gui_modules="Modules",gui_layout="Placement",gui_quick="Actions rapides",gui_lock="Verrouiller les éléments",gui_unlock="Déverrouiller les éléments",gui_open_hub="Ouvrir le Hub Mythique+",gui_send_keys="Envoyer les clés du groupe",gui_roulette="Roulette de clés",gui_score_preview="Aperçu TomoScore",gui_tracker_preview="Aperçu du tracker",gui_score_last="Dernier run",gui_reset_pos="Réinitialiser la position",gui_enabled="Activé",gui_hide_blizzard="Masquer le tracker Mythique+ Blizzard",gui_show_timer="Afficher le timer",gui_show_forces="Afficher les forces ennemies",gui_show_bosses="Afficher les boss",gui_show_background="Afficher le fond",gui_show_header="Afficher l'en-tête",gui_show_dungeon="Afficher le nom du donjon",gui_splits="Splits du meilleur run",gui_checkpoints="Splits par checkpoints",gui_auto_score="Afficher TomoScore automatiquement en fin de run",gui_auto_key="Insérer automatiquement la clé",gui_keysync="Partager les clés avec les utilisateurs MythicHub",gui_char_skin="Skin de la fiche personnage",gui_inspect_skin="Skin d'inspection",gui_item_info="Niveau d'objet / amélioration",gui_gems="Indicateurs de gemmes",gui_inspect_info="Infos d'objet en inspection",gui_char_movable="Fenêtre personnage déplaçable",gui_only_instance="Afficher seulement en instance",gui_swipe="Afficher la recharge",gui_scale="Échelle",gui_alpha="Opacité",gui_font_scale="Échelle de police",gui_brez_size="Taille du compteur",gui_brez_font="Taille de police",gui_reload_note="Certains changements du skin Personnage/Inspection nécessitent /reload.",gui_preset="Préréglage",gui_objective="Affichage des boss",gui_timer_layout="Disposition du timer",gui_segment="Couleurs du timer",gui_about="Boîte à outils Mythique+ autonome en bleu azur et blanc, issue des systèmes Mythique+ de TomoMod.",gui_advisor="Conseiller de clé",gui_advisor_btn="Suggérer le prochain donjon",
}
for k,v in pairs(T) do L[k]=v end
