if GetLocale() ~= "frFR" then return end
local L=MythicHub_L
local T={
 mhub_title="HUB MYTHIQUE+",mhub_col_dungeon="Donjon",mhub_col_level="Clé",mhub_col_rating="Score",mhub_col_best="Meilleur",
 mhub_tp_click="Cliquer pour se téléporter",mhub_tp_not_available="Téléportation indisponible",mhub_tp_not_learned="Téléportation du donjon non apprise.",
 mhub_vault_title="GRANDE CHAMBRE-FORTE",mhub_vault_raids="Raids",mhub_vault_dungeons="Donjons",mhub_vault_world="Monde",mhub_vault_locked="Récompense pas encore débloquée",
 mover_battlerez="Résurrection de combat",msg_char_skin_reload="Skin Personnage : /reload pour appliquer tous les changements.",
 tmt_completed_depleted="CLÉ ÉPUISÉE",tmt_completed_on_time="CLÉ TERMINÉE",tmt_deaths="Morts",tmt_dungeon_unknown="Donjon Mythique+",tmt_forces="Forces ennemies",tmt_forces_done="TERMINÉ",tmt_forces_pct="%d%%",tmt_forces_remaining="%d restantes",tmt_key_level="+%d",tmt_key_none_found="Aucune clé Mythique+ trouvée",tmt_key_not_available="Synchronisation des clés indisponible",tmt_key_not_in_group="Vous n'êtes pas dans un groupe",tmt_kr_spin="LANCER",tmt_preview_active="Aperçu du tracker Mythique+ activé.",tmt_preview_hidden="Aperçu du tracker Mythique+ masqué.",tmt_preview_dungeon_name="Autel des crochets",tmt_time_lost="Temps perdu : %s",
 ts_col_player="Joueur",ts_col_rating="Cote",ts_col_key_level="Clé",ts_col_key_name="Donjon",ts_completed="TERMINÉ",ts_depleted="ÉPUISÉ",ts_duration="Durée",ts_footer_total="Groupe",ts_footer_players="%d joueurs",ts_key_level="+%d",ts_mythic_zero="Mythique 0",ts_no_data="Aucune donnée de run Mythique+ sauvegardée.",
 gui_subtitle="Centre de commande Mythique+ autonome",gui_dashboard="Tableau de bord",gui_tracker="Tracker",gui_keys_score="Clés & Score",gui_character="Personnage & Inspection",gui_brez="Résurrection",gui_modules="Modules",gui_layout="Placement",gui_quick="Actions rapides",gui_lock="Verrouiller les éléments",gui_unlock="Déverrouiller les éléments",gui_open_hub="Ouvrir le Hub Mythique+",gui_send_keys="Envoyer les clés du groupe",gui_roulette="Roulette de clés",gui_score_preview="Aperçu MythicHubScore",gui_tracker_preview="Aperçu du tracker",gui_score_last="Dernier run",gui_reset_pos="Réinitialiser la position",gui_enabled="Activé",gui_hide_blizzard="Masquer le tracker Mythique+ Blizzard",gui_show_timer="Afficher le timer",gui_show_forces="Afficher les forces ennemies",gui_show_bosses="Afficher les boss",gui_show_background="Afficher le fond",gui_show_header="Afficher l'en-tête",gui_show_dungeon="Afficher le nom du donjon",gui_splits="Splits du meilleur run",gui_checkpoints="Splits par checkpoints",gui_auto_score="Afficher MythicHubScore automatiquement en fin de run",gui_auto_key="Insérer automatiquement la clé",gui_keysync="Partager les clés avec les utilisateurs MythicHub",gui_char_skin="Skin de la fiche personnage",gui_inspect_skin="Skin d'inspection",gui_item_info="Niveau d'objet / amélioration",gui_gems="Indicateurs de gemmes",gui_inspect_info="Infos d'objet en inspection",gui_char_movable="Fenêtre personnage déplaçable",gui_only_instance="Afficher seulement en instance",gui_swipe="Afficher la recharge",gui_scale="Échelle",gui_alpha="Opacité",gui_font_scale="Échelle de police",gui_brez_size="Taille du compteur",gui_brez_font="Taille de police",gui_reload_note="Certains changements du skin Personnage/Inspection nécessitent /reload.",gui_preset="Préréglage",gui_objective="Affichage des boss",gui_timer_layout="Disposition du timer",gui_segment="Couleurs du timer",gui_about="Boîte à outils Mythique+ autonome en bleu azur et blanc, issue des systèmes Mythique+ de TomoMod.",gui_display="Affichage",gui_style_progress="Style & progression",gui_size_opacity="Taille & opacité",gui_keystones="Clés mythiques",gui_tomoscore="MythicHubScore",gui_character_sheet="Fiche personnage",gui_midnight_enchants="Affichage des enchantements Midnight",gui_integrated_mplus="Infos Mythique+ intégrées",gui_mplus_info_text="Le skin conserve le widget de score Mythique+ de TomoMod. Cliquer sur le score ouvre l'aperçu MythicHub avec les donjons de saison, meilleurs runs, téléportations et progression du Grand coffre.",gui_counter="Compteur",gui_how_it_works="Fonctionnement",gui_brez_help_text="Le compteur lit les charges mutualisées de résurrection de combat via l'API du jeu. Il affiche les charges restantes et la recharge sans analyse du journal de combat, et peut être déplacé avec /mh unlock.",gui_advisor="Conseiller de clé",gui_advisor_btn="Suggérer le prochain donjon",
gui_score_name="MythicHubScore",gui_unlock_score="Déverrouiller MythicHubScore",gui_lock_score="Verrouiller MythicHubScore",gui_character_scale="Échelle de la fiche personnage",
 gui_progression="Progression",gui_run_history="Historique des runs",gui_score_planner="Planificateur de score / Améliorations",gui_minimap="Bouton de minicarte",gui_history_max="Nombre maximum de runs sauvegardés",gui_open_history="Ouvrir l'historique",gui_open_planner="Ouvrir le planificateur",gui_sync_history="Synchroniser l'historique Blizzard",gui_clear_history="Effacer l'historique (Maj+Clic)",gui_target_increase="Augmentation de clé ciblée",
 history_title="Historique des runs MythicHub",history_sync="Synchroniser Blizzard",history_clear="Effacer l'historique",history_shift_clear="Maintenez Maj en cliquant sur Effacer l'historique.",history_col_date="Date",history_col_dungeon="Donjon",history_col_key="Clé",history_col_time="Temps",history_col_score="Score",history_col_gain="Gain",history_col_status="Statut",history_timed="DANS LES TEMPS",history_depleted="ÉPUISÉE",history_complete="TERMINÉ",history_summary="%d runs  •  %d dans les temps  •  %d épuisés  •  %+d cote",
 planner_title="Planificateur de score MythicHub",planner_subtitle="Upgrade Finder — classe les meilleures améliorations Mythique+ à partir de vos données de saison.",planner_refresh="Actualiser",planner_overall="Cote : %d",planner_col_dungeon="Donjon",planner_col_best="Meilleur",planner_col_score="Score",planner_col_target="Objectif",planner_col_gain="Gain estimé",planner_col_action="Voyage",planner_tp="TP",planner_estimate_note="Les gains sont estimés à partir de votre propre courbe score/niveau de la saison. La cote exacte attribuée par Blizzard peut varier selon le temps et les règles de score de la saison.",planner_no_data="Aucune donnée de donjon de saison disponible.",planner_combat="Le planificateur de score ne peut pas être ouvert en combat.",planner_chat_pick="Upgrade Finder : %s +%d — gain estimé ~+%d.",
 minimap_open_config="Ouvrir les réglages",minimap_open_hub="Ouvrir le Hub Mythique+",minimap_open_history="Ouvrir l'historique",minimap_open_planner="Ouvrir le planificateur",minimap_tooltip="Clic gauche : réglages. Clic droit : menu MythicHub. Faites glisser pour déplacer autour de la minicarte.",minimap_compartment_tooltip="Cliquez pour ouvrir le menu rapide MythicHub.",
}
for k,v in pairs(T) do L[k]=v end
