if GetLocale() ~= "itIT" then return end
local L=MythicHub_L
local T={mhub_title="HUB MITICHE+",mhub_col_dungeon="Spedizione",mhub_col_level="Chiave",mhub_col_rating="Punteggio",mhub_col_best="Migliore",mhub_tp_click="Clicca per teletrasportarti",mhub_tp_not_available="Teletrasporto non disponibile",mhub_tp_not_learned="Teletrasporto della spedizione non appreso.",mhub_vault_title="GRANDE CAMERA",mhub_vault_raids="Incursioni",mhub_vault_dungeons="Spedizioni",mhub_vault_world="Mondo",mhub_vault_locked="Ricompensa non ancora sbloccata",mover_battlerez="Resurrezione in combattimento",msg_char_skin_reload="Skin personaggio: /reload per applicare tutte le modifiche.",tmt_completed_depleted="CHIAVE ESAURITA",tmt_completed_on_time="CHIAVE COMPLETATA",tmt_deaths="Morti",tmt_dungeon_unknown="Spedizione Mitica+",tmt_forces="Forze nemiche",tmt_forces_done="FATTO",tmt_forces_remaining="%d rimanenti",tmt_key_none_found="Nessuna chiave Mitica+ trovata",tmt_key_not_available="Sincronizzazione chiavi non disponibile",tmt_key_not_in_group="Non sei in un gruppo",tmt_kr_spin="GIRA",tmt_preview_active="Anteprima tracker Mitica+ attivata.",tmt_time_lost="Tempo perso: %s",ts_col_player="Giocatore",ts_col_rating="Punteggio",ts_col_key_level="Chiave",ts_col_key_name="Spedizione",ts_completed="COMPLETATA",ts_depleted="ESAURITA",ts_duration="Durata",ts_footer_total="Gruppo",ts_footer_players="%d giocatori",ts_mythic_zero="Mitica 0",ts_no_data="Nessun dato Mitica+ salvato.",gui_subtitle="Centro di comando Mitica+ standalone",gui_dashboard="Panoramica",gui_tracker="Tracker",gui_keys_score="Chiavi e Score",gui_character="Personaggio e Ispezione",gui_brez="Battle Rez",gui_modules="Moduli",gui_quick="Azioni rapide",gui_lock="Blocca elementi",gui_unlock="Sblocca elementi",gui_open_hub="Apri Hub Mitica+",gui_send_keys="Invia chiavi del gruppo",gui_roulette="Roulette chiavi",gui_score_preview="Anteprima Score",gui_tracker_preview="Anteprima tracker",gui_score_last="Ultima run",gui_reset_pos="Ripristina posizione",gui_enabled="Attivo",gui_hide_blizzard="Nascondi tracker Mitica+ Blizzard",gui_show_timer="Mostra timer",gui_show_forces="Mostra forze nemiche",gui_show_bosses="Mostra boss",gui_auto_score="Mostra MythicHubScore automaticamente a fine run",gui_auto_key="Inserisci automaticamente la chiave",gui_keysync="Condividi chiavi con utenti MythicHub",gui_only_instance="Mostra solo nelle istanze",gui_scale="Scala",gui_alpha="Opacità",gui_font_scale="Scala carattere",gui_brez_size="Dimensione contatore",gui_brez_font="Dimensione carattere",gui_advisor="Consigliere chiave",gui_advisor_btn="Suggerisci prossima spedizione",gui_score_name="MythicHubScore",gui_unlock_score="Sblocca MythicHubScore",gui_lock_score="Blocca MythicHubScore",gui_character_scale="Scala finestra personaggio",
 gui_progression="Progressione",gui_run_history="Cronologia run",gui_score_planner="Pianificatore punteggio / Upgrade",gui_minimap="Pulsante minimappa",gui_history_max="Numero massimo di run salvate",gui_open_history="Apri cronologia",gui_open_planner="Apri pianificatore",gui_sync_history="Sincronizza cronologia Blizzard",gui_clear_history="Cancella cronologia (Maiusc+Clic)",gui_target_increase="Aumento chiave obiettivo",
 history_title="Cronologia run MythicHub",history_sync="Sincronizza Blizzard",history_clear="Cancella cronologia",history_shift_clear="Tieni premuto Maiusc mentre clicchi Cancella cronologia.",history_col_date="Data",history_col_dungeon="Spedizione",history_col_key="Chiave",history_col_time="Tempo",history_col_score="Punteggio",history_col_gain="Guadagno",history_col_status="Stato",history_timed="IN TEMPO",history_depleted="ESAURITA",history_complete="FATTO",history_summary="%d run  •  %d in tempo  •  %d esaurite  •  %+d punteggio",
 planner_title="Pianificatore punteggio MythicHub",planner_subtitle="Upgrade Finder — ordina i migliori miglioramenti Mitica+ usando i dati della tua stagione.",planner_refresh="Aggiorna",planner_overall="Punteggio: %d",planner_col_dungeon="Spedizione",planner_col_best="Migliore",planner_col_score="Punteggio",planner_col_target="Obiettivo",planner_col_gain="Guadagno stim.",planner_col_action="Viaggio",planner_tp="TP",planner_estimate_note="I guadagni stimati usano la tua curva personale punteggio/livello della stagione. Il punteggio Blizzard effettivo può variare in base al tempo e alle regole stagionali.",planner_no_data="Nessun dato stagionale disponibile.",planner_combat="Il pianificatore punteggio non può essere aperto in combattimento.",planner_chat_pick="Upgrade Finder: %s +%d — guadagno stimato ~+%d.",
 minimap_open_config="Apri impostazioni",minimap_open_hub="Apri Hub Mitica+",minimap_open_history="Apri cronologia",minimap_open_planner="Apri pianificatore",minimap_tooltip="Clic sinistro: impostazioni. Clic destro: menu MythicHub. Trascina per spostare attorno alla minimappa.",minimap_compartment_tooltip="Clicca per aprire il menu rapido MythicHub.",
}
for k,v in pairs(T) do L[k]=v end
