if GetLocale() ~= "ptBR" then return end
local L=MythicHub_L
local T={mhub_title="HUB MÍTICO+",mhub_col_dungeon="Masmorra",mhub_col_level="Pedra",mhub_col_rating="Pontuação",mhub_col_best="Melhor",mhub_tp_click="Clique para teleportar",mhub_tp_not_available="Teleporte indisponível",mhub_tp_not_learned="Teleporte da masmorra não aprendido.",mhub_vault_title="GRANDE COFRE",mhub_vault_raids="Raides",mhub_vault_dungeons="Masmorras",mhub_vault_world="Mundo",mhub_vault_locked="Recompensa ainda não desbloqueada",mover_battlerez="Ressurreição em combate",msg_char_skin_reload="Visual do personagem: /reload para aplicar todas as alterações.",tmt_completed_depleted="PEDRA ESGOTADA",tmt_completed_on_time="PEDRA CONCLUÍDA",tmt_deaths="Mortes",tmt_dungeon_unknown="Masmorra Mítica+",tmt_forces="Forças inimigas",tmt_forces_done="CONCLUÍDO",tmt_forces_remaining="%d restantes",tmt_key_none_found="Nenhuma pedra Mítica+ encontrada",tmt_key_not_available="Sincronização de pedras indisponível",tmt_key_not_in_group="Você não está em um grupo",tmt_kr_spin="GIRAR",tmt_preview_active="Prévia do tracker Mítico+ ativada.",tmt_time_lost="Tempo perdido: %s",ts_col_player="Jogador",ts_col_rating="Pontuação",ts_col_key_level="Pedra",ts_col_key_name="Masmorra",ts_completed="CONCLUÍDA",ts_depleted="ESGOTADA",ts_duration="Duração",ts_footer_total="Grupo",ts_footer_players="%d jogadores",ts_mythic_zero="Mítico 0",ts_no_data="Nenhum dado de Mítico+ salvo.",gui_subtitle="Central independente para Mítico+",gui_dashboard="Painel",gui_tracker="Tracker",gui_keys_score="Pedras e Score",gui_character="Personagem e Inspeção",gui_brez="Ressurreição",gui_modules="Módulos",gui_quick="Ações rápidas",gui_lock="Bloquear elementos",gui_unlock="Desbloquear elementos",gui_open_hub="Abrir Hub Mítico+",gui_send_keys="Enviar pedras do grupo",gui_roulette="Roleta de pedras",gui_score_preview="Prévia do Score",gui_tracker_preview="Prévia do tracker",gui_score_last="Última run",gui_reset_pos="Redefinir posição",gui_enabled="Ativado",gui_hide_blizzard="Ocultar tracker Mítico+ da Blizzard",gui_show_timer="Mostrar cronômetro",gui_show_forces="Mostrar forças inimigas",gui_show_bosses="Mostrar chefes",gui_auto_score="Mostrar MythicHubScore automaticamente no fim da run",gui_auto_key="Inserir pedra automaticamente",gui_keysync="Compartilhar pedras com usuários MythicHub",gui_only_instance="Mostrar apenas em instâncias",gui_scale="Escala",gui_alpha="Opacidade",gui_font_scale="Escala da fonte",gui_brez_size="Tamanho do contador",gui_brez_font="Tamanho da fonte",gui_advisor="Consultor de pedra",gui_advisor_btn="Sugerir próxima masmorra",gui_score_name="MythicHubScore",gui_unlock_score="Desbloquear MythicHubScore",gui_lock_score="Bloquear MythicHubScore",gui_character_scale="Escala da janela de personagem",
 gui_progression="Progressão",gui_run_history="Histórico de runs",gui_score_planner="Planejador de pontuação / Melhorias",gui_minimap="Botão do minimapa",gui_history_max="Máximo de runs salvas",gui_open_history="Abrir histórico",gui_open_planner="Abrir planejador",gui_sync_history="Sincronizar histórico da Blizzard",gui_clear_history="Limpar histórico (Shift+Clique)",gui_target_increase="Aumento de pedra alvo",
 history_title="Histórico de runs MythicHub",history_sync="Sincronizar Blizzard",history_clear="Limpar histórico",history_shift_clear="Segure Shift ao clicar em Limpar histórico.",history_col_date="Data",history_col_dungeon="Masmorra",history_col_key="Pedra",history_col_time="Tempo",history_col_score="Pontuação",history_col_gain="Ganho",history_col_status="Status",history_timed="NO TEMPO",history_depleted="ESGOTADA",history_complete="CONCLUÍDA",history_summary="%d runs  •  %d no tempo  •  %d esgotadas  •  %+d pontuação",
 planner_title="Planejador de pontuação MythicHub",planner_subtitle="Upgrade Finder — classifica as melhores melhorias Mítico+ usando seus dados da temporada.",planner_refresh="Atualizar",planner_overall="Pontuação: %d",planner_col_dungeon="Masmorra",planner_col_best="Melhor",planner_col_score="Pontuação",planner_col_target="Alvo",planner_col_gain="Ganho estim.",planner_col_action="Viagem",planner_tp="TP",planner_estimate_note="Os ganhos estimados usam sua própria curva de pontuação/nível da temporada. A pontuação exata da Blizzard pode variar com o tempo e as regras da temporada.",planner_no_data="Ainda não há dados de masmorras da temporada.",planner_combat="O planejador de pontuação não pode ser aberto em combate.",planner_chat_pick="Upgrade Finder: %s +%d — ganho estimado ~+%d.",
 minimap_open_config="Abrir configurações",minimap_open_hub="Abrir Hub Mítico+",minimap_open_history="Abrir histórico",minimap_open_planner="Abrir planejador",minimap_tooltip="Clique esquerdo: configurações. Clique direito: menu MythicHub. Arraste para mover ao redor do minimapa.",minimap_compartment_tooltip="Clique para abrir o menu rápido do MythicHub.",
}
for k,v in pairs(T) do L[k]=v end
